### ISSUE TITLE
Brightness bar doesn't show up

### ISSUE THREAD

**Issue by jsb5151** [lawtancool/homeassistant-control4#5]
HA Core 0.107.6, latest pull of the homeassistant-control4 component.  EA-3 running 3.1.2, C4-KD120 exposed.  On/off switch works but I get no brightness bar.

Configuration snippet:

  - platform: control4
    base_url: 'http://10.1.10.40:9000/'
    proxy_id: 234
    name: Chandelier HTTP
    scan_interval: 10

**Comment by samlambert** [comment]
I am getting the same issue.

**Comment by samlambert** [comment]
I've narrowed it down to this exception.

```
2020-04-12 20:51:57 ERROR (MainThread) [custom_components.control4.light] Error while fetch data.
Traceback (most recent call last):
  File "/config/custom_components/control4/light.py", line 148, in async_update
    request = yield from websession.get(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
2020-04-12 20:51:57 ERROR (MainThread) [custom_components.control4.light] Error while fetch data.
Traceback (most recent call last):
  File "/config/custom_components/control4/light.py", line 148, in async_update
    request = yield from websession.get(url)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/usr/local/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None
```

**Comment by samlambert** [comment]
https://github.com/lawtancool/homeassistant-control4/pull/6 fixed the issue for me.
