### ISSUE TITLE
Help!!! Since Hassio update 0.118.0 Control 4 integration is broken

### ISSUE THREAD

**Issue by tkcreddy** [lawtancool/homeassistant-control4#9]
Sir,

I have been using your implementation for last one year. Since 0.118.0 update last night my control 4 integration is broken with below error for lights, climate and alarm. Please help. 

2020-11-20 04:35:41 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.upstairs fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/control4_kr/climate.py", line 298, in async_update
    yield from request.release()
TypeError: 'noop' object is not iterable
2020-11-20 04:35:41 ERROR (MainThread) [homeassistant.helpers.entity] Update for light.living_light fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/config/custom_components/control4_kr/light.py", line 162, in async_update
    yield from request.release()
TypeError: 'noop' object is not iterable

**Comment by MrBradford** [comment]
I'm not the dev, but from what I can tell it seems to be some change to the way web sessions are handled. I was able to get everything working by rolling back to 117.6.

**Comment by ramellahome** [comment]
just installed this, and it would seem the websocket is still an issue. I get " 'noop' object is not iterable" when I try to control anything.
Are there plans to continue fixing this?
I'm on core-2021.4.5 
Home Assistant OS 5.13


Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/control4/light.py:126
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:23:20 AM (1 occurrences)
Last logged: 12:23:20 AM

[139790709510688] 'noop' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 322, in async_handle_light_on_service
    await light.async_turn_on(**params)
  File "/config/custom_components/control4/light.py", line 90, in async_turn_on
    yield from self.update_state(STATE_VARIABLE_ID, 1)
  File "/config/custom_components/control4/light.py", line 126, in update_state
    yield from request.release()
TypeError: 'noop' object is not iterable
